name: Backend CI

on:
  push:
    branches:
      - main
      - develop
      - feature/devops-setup 
  pull_request:
    branches:
      - main
      - develop
      - feature/devops-setup 

jobs:
  build-and-test:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Build with Maven
        working-directory: backend/order-management
        run: mvn clean package -DskipTests

      - name: Run Tests
        working-directory: backend/order-management
        run: mvn test
