name: Frontend CI

on:
  push:
    branches:
      - main
      - develop
      - feature/devops-setup 
  pull_request:
    branches:
      - main
      - develop
      - feature/devops-setup 

jobs:
  build-and-test:
    name: Build & Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        working-directory: frontend/app
        run: npm install

      - name: Run Tests
        working-directory: frontend/app
        run: npm test --if-present

      - name: Build React App
        working-directory: frontend/app
        run: npm run build
